(() => {
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const toast=(msg)=>{let t=$('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2200)};
$$('[data-menu]').forEach(b=>b.addEventListener('click',()=>{$('[data-mobile]')?.classList.toggle('open')}));
$$('[data-toggle]').forEach(el=>el.addEventListener('click',()=>{el.classList.toggle('on'); el.setAttribute('aria-pressed',el.classList.contains('on'))}));
$$('[data-demo-invite]').forEach(b=>b.addEventListener('click',()=>toast('Discord invite is ready to connect when the bot OAuth URL is configured.')));
$$('a[href="#"]').forEach(a=>a.addEventListener('click',e=>e.preventDefault()));
$$('.btn').forEach(b=>{if(b.textContent.includes('Add to Discord')) b.addEventListener('click',e=>{if(b.getAttribute('href')?.endsWith('#get-started')){const target=$('#get-started');if(target){e.preventDefault();target.scrollIntoView({behavior:'smooth'})}}})});
const search=$('[data-search]'); const cmds=$$('[data-command]'); const cats=$$('.category button'); let activeCat='All';
function filter(){if(!cmds.length)return;let q=(search?.value||'').toLowerCase();let shown=0;cmds.forEach(c=>{let cat=$('.badge',c)?.textContent?.trim()||'';let text=c.textContent.toLowerCase();let ok=(!q||text.includes(q))&&(activeCat==='All'||cat.toLowerCase()===activeCat.toLowerCase());c.style.display=ok?'block':'none';if(ok)shown++});let e=$('.empty');if(shown===0&&!e){e=document.createElement('div');e.className='empty';e.textContent='No commands match your search.';$('.cmds')?.appendChild(e)}if(e)e.style.display=shown?'none':'block'}
search?.addEventListener('input',filter); cats.forEach(c=>c.addEventListener('click',()=>{cats.forEach(x=>x.classList.remove('active'));c.classList.add('active');activeCat=c.textContent.trim();filter()}));
$$('.tabs .tab').forEach(tab=>tab.addEventListener('click',()=>{$$('.tabs .tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active');let prefix=tab.textContent.toLowerCase().includes('prefix');cmds.forEach(c=>{const code=$('code',c);if(code){const slash=code.textContent.trim().startsWith('/');c.dataset.mode=prefix?'prefix':'slash';if(prefix && slash){code.textContent=code.textContent.replace(/^\//,'!')}else if(!prefix && !slash){code.textContent=code.textContent.replace(/^!/,'/')}}});filter();}));
$$('button').filter?null:null;
$$('button').forEach(b=>{if(/save/i.test(b.textContent))b.addEventListener('click',()=>{localStorage.setItem('oubot-saved','1');toast('Changes saved successfully');let s=document.createElement('span');s.className='save-state';s.textContent='Saved';b.parentElement?.appendChild(s);setTimeout(()=>s.remove(),1800)})});
$$('input,select').forEach(el=>{let key='oubot-'+(el.getAttribute('aria-label')||el.name||el.previousElementSibling?.textContent||'field').toLowerCase().replace(/[^a-z0-9]+/g,'-');let v=localStorage.getItem(key);if(v!==null)el.value=v;el.addEventListener('change',()=>localStorage.setItem(key,el.value))});
$$('[data-toggle]').forEach((el,i)=>{let key='oubot-toggle-'+i,v=localStorage.getItem(key);if(v!==null)el.classList.toggle('on',v==='1');el.addEventListener('click',()=>localStorage.setItem(key,el.classList.contains('on')?'1':'0'))});
})();